services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 backend.Screening:app
    envVars:
      - key: FLASK_ENV
        value: production
